export const NOT_FOUND_CODE = "NOT_FOUND";
export const UNAUTHENTICATED_CODE = "UNAUTHENTICATED";
export const BAD_USER_INPUT_CODE = "BAD_USER_INPUT";
export const INTERNAL_SERVER_ERROR_CODE = "INTERNAL_SERVER_ERROR";
export const FORBIDDEN_ERROR_CODE = "FORBIDDEN";
